model_list:
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/deepseek-v4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/deepseek-v4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/deepseek-v4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/deepseek-v4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/deepseek-v4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/deepseek-v4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/deepseek-v4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-v4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-v4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-v4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-v4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-v4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-v4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-v4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PRo
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PRo
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PRo
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PRo
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PRo
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PRo
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PRo
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PrO
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PrO
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PrO
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PrO
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PrO
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PrO
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeek-V4-PrO
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeeK-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeeK-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeeK-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeeK-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeeK-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeeK-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeeK-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeEk-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeEk-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeEk-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeEk-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeEk-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeEk-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSeEk-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSEek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSEek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSEek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSEek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSEek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSEek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeepSEek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/Deepseek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/Deepseek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/Deepseek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/Deepseek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/Deepseek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/Deepseek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/Deepseek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeePSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeePSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeePSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeePSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeePSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeePSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeePSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeEpSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY1
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeEpSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY2
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeEpSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY3
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeEpSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY4
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeEpSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY5
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeEpSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY6
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
- model_name: dsv4p
  litellm_params:
    model: openai/deepseek-ai/DeEpSeek-V4-Pro
    api_base: os.environ/MS_BASEURL
    api_key: os.environ/MS_KEY7
    rpm: 1
    timeout: 120
  model_info:
    mode: chat
    max_tokens: 131072
litellm_settings:
  drop_params: false
  json_logs: true
  store_prompts_in_spend_logs: true
  request_timeout: 600
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  background_health_checks: false
router_settings:
  num_retries: 3
  cooldown_time: 20
  routing_strategy: latency-based-routing
  enable_pre_call_checks: true
  allowed_fails_policy:
    BadRequestErrorAllowedFails: 0
    RateLimitErrorAllowedFails: 3
    TimeoutErrorAllowedFails: 3
  latency_based_routing_config:
    lowest_latency_buffer: 0.0
    rolling_window_size: 10
